<template>
    <div class='panel panel-primary'>
        <div class='panel-heading'>
            {{pageTitle}}
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <h2>VSCommands</h2>
                    <p>When I was using the TV as a second monitor I had a requirement to permanently display the editor screens
                        in Visual Studio at a zoom level of around 120%.</p>
                    <p>The way I achieved this was by using a Visual Studio Extension called VSCommands:</p>
                    <a href="http://visualstudiogallery.msdn.microsoft.com/a83505c6-77b3-44a6-b53b-73d77cba84c8">VSCommands for Visual Studio 2012</a>
                    <p>Once installed a VSCommands menu item is available under the TOOLS menu. The Zoom settings can be set in
                        the following screen:</p>
                    <p><img src="./app/assets/images/visualstudio/VSCommandsZoom.png" width="858" height="445" alt="Setting the Zoom level in VSCommands"
                    />
                    </p>
                    <h2>Visual Studio - Escaping the double quotes!</h2>
                    <p>In Visual Studio I find myself editing text files by hand - XAML for example. Intellisense comes in very
                        handy at this point. For example when I start typing an attribute in a XAML tag Visual Studio will provide
                        me with a list of relevant options that match the text I have started to type. You can use the down arrow
                        key to select the desired name from the popup window and then press tab to have it automatically inserted
                        into the text editor along with the ="" text ready for you to type your attribute value in. However,
                        after you have filled the attribute value in it is not easy to escape from the double quotes. </p>
                    <p>In the end I went to TOOLS>OPTIONS>Environment>Keyboard and setup Edit.WordNext to have a shortcut of Shift+Space.
                        Usually the same functionality is achieved with the Ctrl+RightArrow key but I find this new keyboard
                        shortcut more intuitive.</p>
                    <img src="./app/assets/images/visualstudio/WordNextKeyboardShortcut.png" width="757" height="441" alt="Escaping from the Intellisense double quotes by setting up a keyboard shortcut"
                    /><br />
                    <a href="http://stackoverflow.com/questions/1125929/keyboard-command-to-get-out-of-auto-generated-double-quotes">Get out of autogenerated double quotes question on StackOverflow.</a>
                    <h2>Indent Guides</h2>
                    <p>Puts dotted lines between your curly braces - you get the idea!</p>
                    <a href="http://visualstudiogallery.msdn.microsoft.com/e792686d-542b-474a-8c55-630980e72c30">Indent Guides Visual Studio Extension</a>
                    <h2>Commenting and Uncommenting code blocks</h2>
                    <p>Ctrl + E C Comment out</p>
                    <p>Ctrl + E U Uncomment</p>
                    <h1>Navigating errors</h1>
                    <p>Ctrl+Shift+f12 next error</p>
                    <h1>Always run Visual Studio as Administrator</h1>
                    <p>Right click on:</p>
                    <code>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe</code>
                    <p>and select troubleshoot compatibility. Next select troubleshoot program then tick "the program requires additional
                        permissions"</p>
                    <p>Test the program and then click yes save these settings when prompted</p>
                    <h1>Turning on Additional Information during the Build Process</h1>
                    <p>Tools>Options>Projects and Solutions>Build and Run</p>
                    <p>Set the MSBuild project build output verbosity option to the desired setting</p>

                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "VisualStudio"
    }
</script>

<style scoped>

</style>